### ISSUE TITLE
TypeError: col_pre_save() got an unexpected keyword argument 'created'

### ISSUE THREAD

**Issue by mvanaltvorst** [patarapolw/ankisync2#2]
```
Traceback (most recent call last):
  File "main3.py", line 4, in <module>
    apkg = Apkg("/home/mvanaltvorst/Downloads/sample.apkg")
  File "/usr/lib/python3.7/site-packages/ankisync2/anki.py", line 101, in __init__
    super().__init__(self.folder.joinpath("collection.anki2"))
  File "/usr/lib/python3.7/site-packages/ankisync2/anki.py", line 21, in __init__
    db.Col.create()
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6012, in create
    inst.save(force_insert=True)
  File "/usr/lib/python3.7/site-packages/playhouse/signals.py", line 70, in save
    pre_save.send(self, created=created)
  File "/usr/lib/python3.7/site-packages/playhouse/signals.py", line 51, in send
    responses.append((r, r(sender, instance, *args, **kwargs)))
TypeError: col_pre_save() got an unexpected keyword argument 'created'
```

**Comment by patarapolw** [comment]
Sorry for late reply. Shouldn't have `unwatched`.

Fixed with <https://github.com/patarapolw/ankisync2/blob/master/tests/test_readme.py>.

Should be working OK now.
